name: roundnetboard
description: "A new Flutter project."
publish_to: "none"

version: 0.1.0+7

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  material_symbols_icons: ^4.0.575
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  file_picker: ^8.1.4
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  firebase_analytics: ^12.1.0
  share_plus: ^10.1.2
  shared_preferences: ^2.2.3
  provider: ^6.0.0
  feature_discovery: ^0.14.2
  uuid: ^4.5.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter:
  assets:
    - assets/icon/
  uses-material-design: true
